
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AMillionIdeas.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ideas
{

    public System.Guid Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Autor { get; set; }

    public System.DateTime Created { get; set; }

    public int Likes { get; set; }

    public bool Registered { get; set; }

    public Nullable<bool> Colaborative { get; set; }

    public int Position { get; set; }

}

}
