

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AMillionIdeas
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AMillionIdeasDBEntities : DbContext
{
    public AMillionIdeasDBEntities()
        : base("name=AMillionIdeasDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<InfoUsers> InfoUsers { get; set; }

    public virtual DbSet<Idea> Ideas { get; set; }

}

}

